FROM node:20-buster-slim AS base

# 1. Install dependencies only when needed

FROM base AS deps

RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN npm i --legacy-peer-deps

# 2. Rebuild the source code only when needed

FROM base AS builder

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
COPY .env .
RUN npm run build

# 3. Production image, copy all the files and run next

FROM node:20-alpine AS runner

WORKDIR /app

ENV APP_ENV=production

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

USER nextjs
# EXPOSE 3000
# ENV PORT 3000

# CMD node server.js
CMD ["npm","run", "dev"]
